require 'configure/controls/configured/keyword_arguments'
require 'configure/controls/configured/no_arguments'
require 'configure/controls/configured/required_arguments'
require 'configure/controls/configured/subclass'
require 'configure/controls/configured/twice'
